flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- datetime-0.3.1
- mersenne-random-pure64-0.2.2.0
- random-extras-0.19
- snap-loader-static-1.0.0.0
- text-1.2.2.1
resolver: nightly-2016-10-13
